server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: SmSteam123
    url: jdbc:postgresql://service.smssoftwarestudio.com:5432/movies_test_db
    username: moviestestuser
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

